language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
script:
  - node bin/latest_version.js
after_success:
  - npm update
  - node bin/make_bundle.js
  - npm publish
branches:
  only:
    - master
notifications:
  email: false
