language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
script:
  - node bin/latest_version.js
  - npm update
  - node bin/make_bundle.js
deploy:
  provider: npm
  email: ""
  api_key: ""
  on:
    branch: master
notifications:
  email: false
