language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
script:
- echo no-need-to-deploy >RESULT
- node bin/latest_version.js
- RESULT=$(cat RESULT)
- npm install
- npm update
- node bin/make_bundle.js
deploy:
  provider: npm
  email: kyle.cordes@oasisdigital.com
  api_key:
    secure: ng8Y3/AEQD7hiS7yZjA+s8+7Qfs/CP19ucF2DQynNkXgmoT+NMOYt6QW8Uw42qOP2Hfo8kcwMZrnS3hRsDUHimdD9Gv+hZsW0SOBwZanAmbXLMJ8Y0gMr3c7xiOP+DXokX3rAi98oZhi2fH93Nhx+S1eoL1ifXEkRmdxlFLXLDrt5uTa5/kzV2y49N+qNuZGFlzXB7IMhOraaZZiC7CGKEYfYBHtpYXgknF74+Fmhl8i0jWLco1q0srSCmcZljQLY3trIr37HbQgu5PTxuslGNRrd2bqNzjJiHWFRFdus/NtyTiW+UsFvVQYqBf5DHXLxrJCD5ucRy86INY+/A8AxQJe009f2H3GOqThXZCeE3/qNp979B49mRSkaPD1rXo2MITgW+98i1y/MrAKR8Nr8IEARK3ywU9ty87lAwEQ+H6oJUoSCbfIthVKzJuHpn/It+/UhLKkDaS6A5IxAUfleJNU6S0ZK23dgAC0JfbsY60BTwb8sL2+Fj9JM6H43V+4zF3mlrYOreceLgnlHgGYguULMlM25LTCZB/TUZhNJs6brIpvpiNAhaEqj2fed9/aEFjVCyA8GK7pfQDyo+5xeaZndWCuEJFo1iQ1FihePx/AURUNwfnAZdvxXYRgWssMseBF+fTygDaUx6dI20YzxCU96Myd1eSmr2eT9tOIxwE=
  on:
    branch: master
    repo: OasisDigital/rxjs-system-bundle
    condition: "$RESULT = deploy"
  skip_cleanup: true
